# Generated by Otto, do not edit!
#
# This is the Vagrantfile generated by Otto for the development of
# this application/service. It should not be hand-edited. To modify the
# Vagrantfile, use the Appfile.

Vagrant.configure("2") do |config|

  config.vm.clone = ENV["OTTO_VAGRANT_LAYER_PATH"]


  # Host only network
  config.vm.network "private_network", ip: "100.86.106.216"


  # Setup a synced folder from our working directory to /vagrant
  config.vm.synced_folder '/Users/dring/Code/go/src/github.com/dring1/orm', "/opt/gopath/src/github.com/dring1/orm",
    owner: "vagrant", group: "vagrant"


  # Enable SSH agent forwarding so getting private dependencies works
  config.ssh.forward_agent = true

  # Foundation configuration (if any)

  dir = "/otto/foundation-1"
  config.vm.synced_folder '/Users/dring/Code/go/src/github.com/dring1/orm/.otto/compiled/app/foundation-consul/app-dev', dir
  config.vm.provision "shell", inline: "cd #{dir} && bash #{dir}/main.sh"


  # ScriptPacks
  dir = "/otto/scriptpacks"
  config.vm.provision "shell", inline: "sudo rm -rf #{dir}; sudo mkdir -p #{dir}; sudo chmod 0777 #{dir}"


  # Load all our fragments here for any dependencies.

  $preshell = <<SCRIPT
if command -v apt-get >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get update >/dev/null 2>&1
    sudo apt-get install -y apt-transport-https >/dev/null 2>&1
fi
SCRIPT

config.vm.provision "shell", inline: $preshell
config.vm.provision "docker" do |d|
  d.run "redis", args: "-p 6379:6379", image: "redis:latest"
end

# Sync our own dep folder in there
config.vm.synced_folder '/Users/dring/Code/go/src/github.com/dring1/orm/.otto/appfile/deps/0677b6490015e468c6d4c4bef45df457', "/otto-deps/redis-c1d70f76-83e0-b743-dcfe-3df226f71bfa"

# Foundation configuration for dev dep

dir = "/otto/foundation-redis-1"
config.vm.synced_folder '/Users/dring/Code/go/src/github.com/dring1/orm/.otto/compiled/dep-c1d70f76-83e0-b743-dcfe-3df226f71bfa/foundation-consul/app-dev-dep', dir
config.vm.provision "shell", inline: "cd #{dir} && bash #{dir}/main.sh"





  # Use linked clones if possible
  config.vm.provider "virtualbox" do |p|
    p.linked_clone = true
  end

  if Vagrant.has_plugin?("vagrant-parallels", ">= 1.6.0")
    config.vm.provider "parallels" do |p|
      p.linked_clone = true
    end
  end

  # This is to work around some bugs right now
  ["vmware_fusion", "vmware_workstation"].each do |name|
    config.vm.provider(name) do |p|
      p.enable_vmrun_ip_lookup = false
    end
  end



  # Disable the default synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true


  # Make it so that `vagrant ssh` goes directly to the correct dir
  config.vm.provision "shell", inline:
    %Q[echo "cd /opt/gopath/src/github.com/dring1/orm" >> /home/vagrant/.profile]

end
/Users/dring/Code/go/src/github.com/dring1/orm/.otto/compiled/app/dev/Vagrantfile
