#!/bin/bash
set -e

docker rm -f postgres || true && docker run -d -p 54321:5432 --name postgres postgres
docker rm -f pgadmin || true && docker run -p 5050:5050 -d --name pgadmin "thajeztah/pgadmin4"
docker rm -f redis ||true && docker run -d -p 6379:6379 --name redis redis
