#!/bin/bash

docker rm postgres || true && docker run -d -p 5432:54321 --name postgres -e POSTGRES_PASSWORD=password postgres
docker rm redis || true &&  docker run -d -p 6379:6379 --name redis redis
